title: Mon Site Jekyll
description: Un site simple avec LaTeX
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  math_engine: mathjax

title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: false
